"""Update flaskApp

Revision ID: 0ca5e449cb56
Revises: 
Create Date: 2024-06-10 09:31:35.536469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca5e449cb56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'nfcapp_commodity_item_odoo', ['nfcapp_commodity_item_odoo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
