"""Update flaskApp

Revision ID: 16a7e94a089c
Revises: 99ad9ada2a7b
Create Date: 2024-05-20 15:21:20.624943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a7e94a089c'
down_revision = '99ad9ada2a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itemcode_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('product_odoo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('itemcode_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'product_odoo', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 'nfcapp_commodity_item_odoo', ['itemcode_id'], ['id'])

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('itemcode_id')
        batch_op.drop_column('product_id')
        batch_op.drop_column('product_odoo_id')
        batch_op.drop_column('itemcode_code')

    # ### end Alembic commands ###
