"""Update flaskApp

Revision ID: 16bc49f35a05
Revises: 
Create Date: 2024-05-14 23:53:05.620250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16bc49f35a05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_cluster_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('station_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('coordinator', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('puid', sa.Integer(), nullable=True))
        batch_op.drop_column('gps_latitude')
        batch_op.drop_column('province')
        batch_op.drop_column('gps_longitude')
        batch_op.drop_column('is_testing')

    with op.batch_alter_table('nfcapp_station_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gps_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gps_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_testing', sa.Boolean(), nullable=True))
        batch_op.drop_column('desc')
        batch_op.drop_column('code')
        batch_op.drop_column('packing')
        batch_op.drop_column('commodity_id')
        batch_op.drop_column('variant')
        batch_op.drop_column('product_id')
        batch_op.drop_column('commodity_name')
        batch_op.drop_column('puid')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('res_user_odoo', schema=None) as batch_op:
        batch_op.drop_column('groups_name')
        batch_op.drop_column('groups_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('res_user_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groups_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('groups_name', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('nfcapp_station_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('puid', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('commodity_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('variant', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('commodity_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('packing', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_testing')
        batch_op.drop_column('gps_longitude')
        batch_op.drop_column('gps_latitude')
        batch_op.drop_column('province')
        batch_op.drop_column('name')

    with op.batch_alter_table('nfcapp_cluster_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_testing', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gps_longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('province', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gps_latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('puid')
        batch_op.drop_column('code')
        batch_op.drop_column('coordinator')
        batch_op.drop_column('station_name')
        batch_op.drop_column('station_id')

    # ### end Alembic commands ###
