"""Update flaskApp

Revision ID: 1b15b9f7d1bb
Revises: 
Create Date: 2024-05-17 09:30:00.538279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b15b9f7d1bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_code_odoo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'nfcapp_commodity_item_odoo', ['item_code_odoo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('item_code_odoo_id')

    # ### end Alembic commands ###
