"""Update flaskApp

Revision ID: 1f0beb233a91
Revises: 
Create Date: 2024-05-27 15:19:20.263006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0beb233a91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_station_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('write_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_station_odoo', schema=None) as batch_op:
        batch_op.drop_column('write_date')
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
