"""Update flaskApp

Revision ID: 2e8cdd842186
Revises: 
Create Date: 2024-05-28 09:04:02.308261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8cdd842186'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
