"""Update flaskApp

Revision ID: 395afde8a078
Revises: e101f0a6612b
Create Date: 2024-05-28 14:01:20.131773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '395afde8a078'
down_revision = 'e101f0a6612b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_event', schema=None) as batch_op:
        batch_op.alter_column('date_stamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_event', schema=None) as batch_op:
        batch_op.alter_column('date_stamp',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
