"""Update flaskApp

Revision ID: 4b12dc746bb5
Revises: 
Create Date: 2024-06-03 15:24:06.645192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b12dc746bb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_order', schema=None) as batch_op:
        batch_op.drop_column('origin')

    # ### end Alembic commands ###
