"""Update flaskApp

Revision ID: 555118bf76f8
Revises: 
Create Date: 2024-05-30 00:12:26.794865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555118bf76f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_farmer_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certification_status_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_farmer_odoo', schema=None) as batch_op:
        batch_op.drop_column('certification_status_name')

    # ### end Alembic commands ###
