"""Update flaskApp

Revision ID: 5af556381e87
Revises: 1b15b9f7d1bb
Create Date: 2024-05-17 10:00:21.473783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af556381e87'
down_revision = '1b15b9f7d1bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odoo_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('farmer_farmer_odoo_id_fkey', type_='foreignkey')
        batch_op.drop_column('farmer_odoo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farmer_odoo_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('farmer_farmer_odoo_id_fkey', 'nfcapp_farmer_odoo', ['farmer_odoo_id'], ['id'])
        batch_op.drop_column('odoo_id')

    # ### end Alembic commands ###
