"""Update flaskApp

Revision ID: 5c11d2cf1169
Revises: 970b65f63ab2
Create Date: 2024-05-21 01:25:05.772334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c11d2cf1169'
down_revision = '970b65f63ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_farmer_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificaton_status_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_farmer_odoo', schema=None) as batch_op:
        batch_op.drop_column('certificaton_status_id')

    # ### end Alembic commands ###
