"""Update flaskApp

Revision ID: 725f338449a2
Revises: 
Create Date: 2024-05-29 13:41:02.308335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725f338449a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('destination', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_order', schema=None) as batch_op:
        batch_op.drop_column('note')
        batch_op.drop_column('destination')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
