"""Update flaskApp

Revision ID: 76ef6fb72b9c
Revises: 6191ca3a2bcd
Create Date: 2024-06-04 21:41:49.026024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ef6fb72b9c'
down_revision = '6191ca3a2bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commodity_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('variant', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.drop_column('variant')
        batch_op.drop_column('commodity_name')

    # ### end Alembic commands ###
