"""Update flaskApp

Revision ID: 7d40066d4ea0
Revises: 5af556381e87
Create Date: 2024-05-17 10:16:25.868935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d40066d4ea0'
down_revision = '5af556381e87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_product_odoo_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('product_item_code_odoo_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_foreign_key('product_item_code_odoo_id_fkey', 'nfcapp_commodity_item_odoo', ['item_code_odoo_id'], ['id'])
        batch_op.create_foreign_key('product_product_odoo_id_fkey', 'product_odoo', ['product_odoo_id'], ['id'])

    # ### end Alembic commands ###
