"""Update flaskApp

Revision ID: 8326d7c662b1
Revises: 16a7e94a089c
Create Date: 2024-05-21 10:34:48.798844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8326d7c662b1'
down_revision = '16a7e94a089c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_commodity_item_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farmer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('certStatus', sa.String(), nullable=True))

    with op.batch_alter_table('nfcapp_farmer_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certification_status_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_farmer_odoo', schema=None) as batch_op:
        batch_op.drop_column('certification_status_id')

    with op.batch_alter_table('nfcapp_commodity_item_odoo', schema=None) as batch_op:
        batch_op.drop_column('certStatus')
        batch_op.drop_column('farmer_id')

    # ### end Alembic commands ###
