"""Update flaskApp

Revision ID: 852c68676deb
Revises: 
Create Date: 2024-06-04 09:56:38.637607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852c68676deb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('origin', sa.String(), nullable=True))

    with op.batch_alter_table('money', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('purchase_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_id', sa.String(length=36), nullable=True))
        batch_op.drop_column('signature')

    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.drop_column('change_id')

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', sa.BLOB(), nullable=True))
        batch_op.drop_column('change_id')

    with op.batch_alter_table('purchase_event', schema=None) as batch_op:
        batch_op.drop_column('change_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('change_id')

    with op.batch_alter_table('money', schema=None) as batch_op:
        batch_op.drop_column('change_id')

    with op.batch_alter_table('delivery_order', schema=None) as batch_op:
        batch_op.drop_column('origin')
        batch_op.drop_column('change_id')

    # ### end Alembic commands ###
