"""Update flaskApp

Revision ID: 922db69db66e
Revises: e6c83a4cca6e
Create Date: 2024-06-04 10:10:08.449515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922db69db66e'
down_revision = 'e6c83a4cca6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_column('signature')

    # ### end Alembic commands ###
