"""Update flaskApp

Revision ID: 970b65f63ab2
Revises: e5f545965581
Create Date: 2024-05-21 01:19:20.600259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970b65f63ab2'
down_revision = 'e5f545965581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_commodity_item_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farmer_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_commodity_item_odoo', schema=None) as batch_op:
        batch_op.drop_column('farmer_id')

    # ### end Alembic commands ###
