"""Update flaskApp

Revision ID: 99ad9ada2a7b
Revises: c5e46e2a905d
Create Date: 2024-05-20 08:40:00.619719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ad9ada2a7b'
down_revision = 'c5e46e2a905d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_logging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(), nullable=True))
        batch_op.drop_column('action')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_logging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('message')

    # ### end Alembic commands ###
