"""Update flaskApp

Revision ID: a0116e6188f9
Revises: 16bc49f35a05
Create Date: 2024-05-15 00:40:49.318880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0116e6188f9'
down_revision = '16bc49f35a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_station_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_station_odoo', schema=None) as batch_op:
        batch_op.drop_column('puid')

    # ### end Alembic commands ###
