"""Update flaskApp

Revision ID: ad99c57eed34
Revises: 
Create Date: 2024-05-27 10:12:41.987591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad99c57eed34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_cluster_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('write_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('nfcapp_commodity_item_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('write_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('nfcapp_commodity_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('write_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('nfcapp_farmer_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('write_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('product_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('write_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('purchase_order_line_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('write_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('purchase_order_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('write_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('res_user_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('write_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('res_user_odoo', schema=None) as batch_op:
        batch_op.drop_column('write_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('purchase_order_odoo', schema=None) as batch_op:
        batch_op.drop_column('write_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('purchase_order_line_odoo', schema=None) as batch_op:
        batch_op.drop_column('write_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('product_odoo', schema=None) as batch_op:
        batch_op.drop_column('write_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('nfcapp_farmer_odoo', schema=None) as batch_op:
        batch_op.drop_column('write_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('nfcapp_commodity_odoo', schema=None) as batch_op:
        batch_op.drop_column('write_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('nfcapp_commodity_item_odoo', schema=None) as batch_op:
        batch_op.drop_column('write_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('nfcapp_cluster_odoo', schema=None) as batch_op:
        batch_op.drop_column('write_date')
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
