"""Update flaskApp

Revision ID: bd11e2f9a8cb
Revises: c23dd046450b
Create Date: 2024-05-17 10:44:53.898640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd11e2f9a8cb'
down_revision = 'c23dd046450b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_code_list', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.drop_column('item_code_list')

    # ### end Alembic commands ###
