"""Update flaskApp

Revision ID: c23dd046450b
Revises: f8b3f372541e
Create Date: 2024-05-17 10:20:22.487898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23dd046450b'
down_revision = 'f8b3f372541e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_commodity_item_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_commodity_item_odoo', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
