"""Update flaskApp

Revision ID: c586e301e1b5
Revises: 5c11d2cf1169
Create Date: 2024-05-21 01:25:26.222442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c586e301e1b5'
down_revision = '5c11d2cf1169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_farmer_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certification_status_id', sa.Integer(), nullable=True))
        batch_op.drop_column('certificaton_status_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfcapp_farmer_odoo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificaton_status_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('certification_status_id')

    # ### end Alembic commands ###
