"""Update flaskApp

Revision ID: c5e46e2a905d
Revises: bd11e2f9a8cb
Create Date: 2024-05-17 14:32:07.465571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e46e2a905d'
down_revision = 'bd11e2f9a8cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchaser_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cashier_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('purchase_event_purchaser_fkey', type_='foreignkey')
        batch_op.drop_constraint('purchase_event_cashier_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'res_user_odoo', ['purchaser_id'], ['id'])
        batch_op.create_foreign_key(None, 'res_user_odoo', ['cashier_id'], ['id'])
        batch_op.drop_column('purchaser')
        batch_op.drop_column('cashier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cashier', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('purchaser', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('purchase_event_cashier_fkey', 'res_user_odoo', ['cashier'], ['id'])
        batch_op.create_foreign_key('purchase_event_purchaser_fkey', 'res_user_odoo', ['purchaser'], ['id'])
        batch_op.drop_column('cashier_id')
        batch_op.drop_column('purchaser_id')

    # ### end Alembic commands ###
