"""Update flaskApp

Revision ID: d8116eb14fd4
Revises: 
Create Date: 2024-05-30 09:44:52.166953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8116eb14fd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.drop_constraint('expense_purchase_order_id_fkey', type_='foreignkey')
        batch_op.drop_column('purchase_order_id')
        batch_op.drop_column('number')

    with op.batch_alter_table('money', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'expense', ['expense_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('expense_id')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('purchase_order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('expense_purchase_order_id_fkey', 'purchase_order', ['purchase_order_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###
