"""Update flaskApp

Revision ID: e101f0a6612b
Revises: f44b6f7f47fd
Create Date: 2024-05-28 11:28:33.038109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e101f0a6612b'
down_revision = 'f44b6f7f47fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('date_stamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_event', schema=None) as batch_op:
        batch_op.drop_column('date_stamp')
        batch_op.drop_column('note')

    # ### end Alembic commands ###
