"""Update flaskApp

Revision ID: e5f545965581
Revises: 
Create Date: 2024-05-21 00:56:19.682860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f545965581'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_farmer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farmer_name', sa.String(length=120), nullable=True))
        batch_op.drop_column('user_odoo_id')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_farmer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_odoo_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('farmer_name')

    # ### end Alembic commands ###
