"""Update flaskApp

Revision ID: f8b3f372541e
Revises: 7d40066d4ea0
Create Date: 2024-05-17 10:17:35.275133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b3f372541e'
down_revision = '7d40066d4ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('product_odoo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_odoo_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
